// layout.tsx

import type { Metadata } from "next";
import { Playwrite_AU_QLD, Almendra, Inter } from "next/font/google";
import "./globals.css";

import { Providers } from "@/providers/providers";

const playwrite = Playwrite_AU_QLD({
  variable: "--font-playwrite-au",
  weight: ["100", "200", "300", "400"],
});

const almendra = Almendra({
  variable: "--font-almendra",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body
          className={`${inter.variable} ${almendra.variable} ${playwrite.variable} antialiased`}
        >
          {children}
        </body>
      </Providers>
    </html>
  );
}
